language: php

php:
  - 5.5.9
  # - 5.5
  # - 5.6
  # - 7.0
  # - hhvm

sudo: false

services:
  - mysql

before_install:
  - nvm install 5.1

install:
  - ./run-install.sh

before_script:
  - mysql -e 'create database laravel;'
  - export DB_DATABASE=laravel
  - export DB_USERNAME=travis
  - export DB_PASSWORD=

script:  
  - php artisan migrate --force && gulp && vendor/bin/phpunit
